version: "3.8"

services:
  db:
    image: postgres:15
    container_name: dtlabs_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_DB: iot_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: dtlabs_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:senha_segura@db:5432/iot_db
      SECRET_KEY: uma_chave_super_segura
    ports:
      - "8000:8000"

volumes:
  pg_data:
